### ISSUE TITLE
Video-0101 TODO

### ISSUE THREAD

**Issue by eryjus** [eryjus/16bcfs#150]
Video 101 will focus back on the emulator.  There are several components which need to be integrated into the emulator still.  Important components still required are:
* Fetch Register
* Instruction Register
* Program Memory

The goal here is to close the gap between the emulator and the breadboard build.  That said, the breadboard build will need to be updated as well.

This video will target getting the Fetch Register completed.  These tasks will be:

- [x] #28 
- [ ] #153
- [x] #151
- [x] #152

Time permitting:

- [ ] #30

Stretch Goals:

- [ ] #29 
- [ ] Instruction Register Breadboard Update
- [ ] Create the Instruction Register Schematic
- [ ] Create the Instruction Register PCB design
